export const FETCH_CAMPUSES = 'FETCH_CAMPUSES';
export const FETCH_CAMPUS = 'FETCH_CAMPUS';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_STUDENT = 'FETCH_STUDENT';
export const FETCH_STUDENTS_AT_CAMPUS = 'FETCH_STUDENTS_AT_CAMPUS';
export const ADD_CAMPUS = 'ADD_CAMPUS';
export const EDIT_STUDENT = 'EDIT_STUDENT';